# Generated by Django 4.0.1 on 2022-02-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='NW', max_length=2, verbose_name='Раздел'),
        ),
    ]
