# Generated by Django 4.0.1 on 2022-03-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_post_author_alter_post_categorytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'News'), ('AR', 'Article')], default='NW', max_length=2, verbose_name='TypeNews'),
        ),
    ]
